1.	Write a Python Program to Add Two Matrices?
2.	Write a Python Program to Multiply Two Matrices?
3.	Write a Python Program to Transpose a Matrix?
4.	Write a Python Program to Sort Words in Alphabetic Order?
5.	Write a Python Program to Remove Punctuation From a String?


In [7]:
row1 = int(input("Enter the number of rows:"))
col1 = int(input("Enter the number of column"))
row2 = int(input("Enter the number of rows:"))
col2 = int(input("Enter the number of column"))
matrix1=np.mat(range(0,10)).reshape(row1,col1)
matrix2=np.mat(range(10,20)).reshape(row2,col2)
print(matrix1)
print(matrix2)

Enter the number of rows:2
Enter the number of column5
Enter the number of rows:2
Enter the number of column5
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[10 11 12 13 14]
 [15 16 17 18 19]]


In [77]:
a = int(input("Enter the number of rows:"))
b = int(input("Enter the number of column"))
c = int(input("Enter the number of rows:"))
d = int(input("Enter the number of column"))
total1 = a*b
total2 = c*d
matrix3=np.random.randint(0,100,total1).reshape(a,b)
matrix4=np.random.randint(100,1000,total2).reshape(c,d)
matrix3 = np.mat(matrix3)
matrix4 = np.mat(matrix4)
print(matrix3)
print(matrix4)



#Write a Python Program to Add Two Matrices?
#Write a Python Program to Multiply Two Matrices?
#Write a Python Program to Transpose a Matrix?


choice = int(input("Choose 1or2or3 where\n 1.Add Two Matrices\n 2.Multiply Two Matrices\n 3.Transpose a Matrix\n"))
if choice == 1:
    if a==c and b==d:
        print("Addition is possible")
        sum = 0
        sum = matrix3 + matrix4
        sum = np.mat(sum)
        print(" Matrix after adding matrix3 and matrix4 is\n", sum)
    else:
        print("Invalid dimensions of the two matrix, for addition of matrices it is required to have rows and columns of matrix3 should be equal to rows and columns of matrix 4")
if choice == 2:
    if b==c:
        print("Multiplication is possible")
        multipliedvalue = matrix3 * matrix4
        multipliedvalue = np.mat(multipliedvalue)
        
        print("Matrix after multiplication is", multipliedvalue)
    else:
        print("Multiplication is not possible: For multiplication of matrix:\n number of columns of matrix3 should be equal to number of rows of matrix4")
if choice ==3:
    select = int(input("Select 1 or 2\n: 1.matrix3\n  2.matrix4"))
    if select == 1:
        newmatrix = np.transpose(matrix3)
        print("matrix after transpose\n",newmatrix)
    elif select ==2:
        newmatrix = np.transpose(matrix4)
        print("matrix after transpose\n",newmatrix)
    else:
        print("invalid selection, try again")
    

Enter the number of rows:2
Enter the number of column3
Enter the number of rows:2
Enter the number of column3
[[63 62 50]
 [59  8 91]]
[[752 879 512]
 [625 463 537]]
Choose 1or2or3 where
 1.Add Two Matrices
 2.Multiply Two Matrices
 3.Transpose a Matrix
3
Select 1 or 2
: 1.matrix3
  2.matrix42
matrix after transpose
 [[752 625]
 [879 463]
 [512 537]]


In [120]:
para = "Machine learning ,,,is a branch of artificial intelligence focused on building applications that learn from data and improve their accuracy over time without being programmed to do so. In data science, an algorithm is a sequence of statistical processing steps."
para=para.lower()
l=list(para.split())
print(l)
l.sort()
print("\nsorted list is\n",l)

['machine', 'learning', ',,,is', 'a', 'branch', 'of', 'artificial', 'intelligence', 'focused', 'on', 'building', 'applications', 'that', 'learn', 'from', 'data', 'and', 'improve', 'their', 'accuracy', 'over', 'time', 'without', 'being', 'programmed', 'to', 'do', 'so.', 'in', 'data', 'science,', 'an', 'algorithm', 'is', 'a', 'sequence', 'of', 'statistical', 'processing', 'steps.']

sorted list is
 [',,,is', 'a', 'a', 'accuracy', 'algorithm', 'an', 'and', 'applications', 'artificial', 'being', 'branch', 'building', 'data', 'data', 'do', 'focused', 'from', 'improve', 'in', 'intelligence', 'is', 'learn', 'learning', 'machine', 'of', 'of', 'on', 'over', 'processing', 'programmed', 'science,', 'sequence', 'so.', 'statistical', 'steps.', 'that', 'their', 'time', 'to', 'without']


In [131]:
#Write a Python Program to Remove Punctuation From a String
para=para.replace(",","")
para=para.replace(".","")
para

'machine learning is a branch of artificial intelligence focused on building applications that learn from data and improve their accuracy over time without being programmed to do so in data science an algorithm is a sequence of statistical processing steps'