1.	Write a Python Program to find sum of array?
2.	Write a Python Program to find largest element in an array?
3.	Write a Python Program for array rotation?
4.	Write a Python Program to Split the array and add the first part to the end?
5.	Write a Python Program to check if given array is Monotonic?


In [1]:
import numpy as np

In [2]:

arr1 = np.random.randint(0,100,10)
arr1

array([94, 82, 33, 68, 44, 27, 73, 53, 81, 11])

In [3]:
#Write a Python Program to find sum of array
sum=0
for i in range(len(arr1)):
    sum=sum+arr1[i]
print("the sum of arr1 is",sum)    

the sum of arr1 is 566


In [4]:
#Write a Python Program to find largest element in an array?
arr1.max()

94

In [5]:
#Write a Python Program for array rotation
arr1[::-1]

array([11, 81, 53, 73, 27, 44, 68, 33, 82, 94])

In [60]:
arr2 = arr1.copy()
arr2

array([94, 82, 33, 68, 44, 27, 73, 53, 81, 11])

In [56]:
#Write a Python Program to Split the array and add the first part to the end?
start_index = int(input("Enter start index for slicing here: "))
end_index   = int(input("Enter end   index for slicing here: "))

for i in range(start_index,end_index):
    arr2 = np.append(arr2, arr2[i])
print(arr2)
for i in range(end_index-1,start_index-1,-1):
    arr2 = np.delete(arr2, i)
print(arr2)    

Enter start index for slicing here: 3
Enter end   index for slicing here: 6
[94 82 33 68 44 27 73 53 81 11 68 44 27]
[94 82 33 73 53 81 11 68 44 27]


In [73]:
arr2 = arr1.copy()
arr2
start_index = int(input("Enter start index for slicing here: "))
end_index   = int(input("Enter end   index for slicing here: "))
if start_index < end_index:
    if start_index >=0 and end_index <= len(arr2):
        for i in range(start_index,end_index):
            arr2 = np.append(arr2, arr2[i])
        print(arr2)
        for i in range(end_index-1,start_index-1,-1):
            arr2 = np.delete(arr2, i)
        print(arr2)  
    else:
        print("Invalid indices entered")
elif start_index > end_index:
    if (start_index <=len(arr2) and end_index >= 0):
        temp_s = end_index+1
        temp_e = start_index+1
        start_index = temp_s
        end_index = temp_e
    
        for i in range(start_index,end_index):
            arr2 = np.append(arr2, arr2[i])
        print(arr2)
        for i in range(end_index-1,start_index-1,-1):
            arr2 = np.delete(arr2, i)
        print(arr2) 
    else:
        print("*")

Enter start index for slicing here: 5
Enter end   index for slicing here: 2
[94 82 33 68 44 27 73 53 81 11 68 44 27]
[94 82 33 73 53 81 11 68 44 27]


In [95]:
#Write a Python Program to check if given array is Monotonic?
def isMonotonic(array):
    if all (array[i]<=array[i+1] for i in range(len(array)-1)): 
         print("Increasing Monotonic" )
    elif all (array[i]>=array[i+1] for i in range(len(array)-1)): 
         print("Decreasing Monotonic Array")
    else:
        return("Non Monotonic")
isMonotonic([11,10,4,3])

Decreasing Monotonic Array
